<aside class="color-family color-family__primary">
  <h3>Primary</h3>

  {% set color = colors[0] %}
  {% include '../../../framework/design/decorations/color-swatch/--rectangle/color-swatch--rectangle.html.swig' %}

  {% set color = colors[1] %}
  {% include '../../../framework/design/decorations/color-swatch/--rectangle/color-swatch--rectangle.html.swig' %}

  {% set color = colors[2] %}
  {% include '../../../framework/design/decorations/color-swatch/--rectangle/color-swatch--rectangle.html.swig' %}
</aside>
