<section class="home__example home__example--active">
  <h3>Example</h3>

  {% include '../../../project/big-text/big-text.html.swig' %}
  {% include '../../../project/inverted-text/inverted-text.html.swig' %}
  {% include '../../../project/different-section/different-section.html.swig' %}
  {% include '../../../project/call-to-action/call-to-action.html.swig' %}
  {# include '../../../project/tab/tab.html.swig' #}
  {% include '../../../project/features/features.html.swig' %}
</section>
